update CASOS_MUNICIPIOS set MUNICIPIO='Agrón' where MUNICIPIO='AgrÃ³n'
update CASOS_MUNICIPIOS set MUNICIPIO='Alájar' where MUNICIPIO='AlÃ¡jar'
update CASOS_MUNICIPIOS set MUNICIPIO='Órgiva' where MUNICIPIO='Ã“rgiva'
update CASOS_MUNICIPIOS set MUNICIPIO='Écija' where MUNICIPIO='Ã‰cija'
update CASOS_MUNICIPIOS set MUNICIPIO='Alanís' where MUNICIPIO='AlanÃ­s'
update CASOS_MUNICIPIOS set MUNICIPIO='Albanchez de Mágina' where MUNICIPIO='Albanchez de Ãšbeda'
update CASOS_MUNICIPIOS set MUNICIPIO='Albanchez de Mágina' where MUNICIPIO='Albanchez de MÃ¡gina'
update CASOS_MUNICIPIOS set MUNICIPIO='Albondón' where MUNICIPIO='AlbondÃ³n'
update CASOS_MUNICIPIOS set MUNICIPIO='Albuñán' where MUNICIPIO='AlbuÃ±Ã¡n'
update CASOS_MUNICIPIOS set MUNICIPIO='Albuñol' where MUNICIPIO='AlbuÃ±ol'
update CASOS_MUNICIPIOS set MUNICIPIO='Albuñuelas' where MUNICIPIO='AlbuÃ±uelas'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcázar y Bargis' where MUNICIPIO='AlcÃ¡zar y Bargis'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcázar y Fregenite' where MUNICIPIO='AlcÃ¡zar y Fregenite'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcóntar' where MUNICIPIO='AlcÃ³ntar'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcalá de Guadaíra' where MUNICIPIO='AlcalÃ¡ de GuadaÃ­ra'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcalá de Guadaíra' where MUNICIPIO='AlcalÃ¡ de Guadaira'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcalá de los Gazules' where MUNICIPIO='AlcalÃ¡ de los Gazules'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcalá del Rí­o' where MUNICIPIO='AlcalÃ¡ del RÃ­o'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcalá del Valle' where MUNICIPIO='AlcalÃ¡ del Valle'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcalá la Real' where MUNICIPIO='AlcalÃ¡ la Real­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcaucín' where MUNICIPIO='AlcaucÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alcolea del Río' where MUNICIPIO='Alcolea del RÃ­o'
update CASOS_MUNICIPIOS set MUNICIPIO='Algámitas' where MUNICIPIO='AlgÃ¡mitas­'
update CASOS_MUNICIPIOS set MUNICIPIO='Algatocín' where MUNICIPIO='AlgatocÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alhama de Almería' where MUNICIPIO='Alhama de AlmerÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alhaurín de la Torre' where MUNICIPIO='AlhaurÃ­n de la Torre­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alhaurín el Grande' where MUNICIPIO='AlhaurÃ­n el Grande­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alhendín' where MUNICIPIO='AlhendÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alicún' where MUNICIPIO='AlicÃºn­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alicún de Ortega' where MUNICIPIO='AlicÃºn de Ortega­'
update CASOS_MUNICIPIOS set MUNICIPIO='Íllar' where MUNICIPIO='Ã�llar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Íllora' where MUNICIPIO='Ã�llora­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almáchar' where MUNICIPIO='AlmÃ¡char­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almócita' where MUNICIPIO='AlmÃ³cita­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almadén de la Plata' where MUNICIPIO='AlmadÃ©n de la Plata­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almegíjar' where MUNICIPIO='AlmegÃ­jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almerí­a' where MUNICIPIO='AlmerÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almerí­a (capital)' where MUNICIPIO='AlmerÃ­a (capital)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almerí­a (distrito)­' where MUNICIPIO='AlmerÃ­a (distrito)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almodóvar del Río' where MUNICIPIO='AlmodÃ³var del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almogía' where MUNICIPIO='AlmogÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Almuñécar' where MUNICIPIO='AlmuÃ±Ã©car­'
update CASOS_MUNICIPIOS set MUNICIPIO='Álora' where MUNICIPIO='Ã�lora­'
update CASOS_MUNICIPIOS set MUNICIPIO='Andújar' where MUNICIPIO='AndÃºjar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Árchez' where MUNICIPIO='Ã�rchez­'
update CASOS_MUNICIPIOS set MUNICIPIO='Armuña de Almanzora' where MUNICIPIO='ArmuÃ±a de Almanzora­'
update CASOS_MUNICIPIOS set MUNICIPIO='Arroyomolinos de León' where MUNICIPIO='Arroyomolinos de LeÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Úbeda' where MUNICIPIO='Ãšbeda­'
update CASOS_MUNICIPIOS set MUNICIPIO='Ítrabo' where MUNICIPIO='Ã�trabo­'
update CASOS_MUNICIPIOS set MUNICIPIO='Axarquía' where MUNICIPIO='AxarquÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Aznalcázar' where MUNICIPIO='AznalcÃ¡zar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Aznalcóllar' where MUNICIPIO='AznalcÃ³llar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bédar' where MUNICIPIO='BÃ©dar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bélmez de la Moraleda' where MUNICIPIO='BÃ©lmez de la Moraleda­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bérchules' where MUNICIPIO='BÃ©rchules­'
update CASOS_MUNICIPIOS set MUNICIPIO='Béznar' where MUNICIPIO='BÃ©znar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Baños de la Encina' where MUNICIPIO='BaÃ±os de la Encina­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bahía de Cádiz-La Janda' where MUNICIPIO='BahÃ­a de CÃ¡diz-La Janda­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bailén' where MUNICIPIO='BailÃ©n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bayárcal' where MUNICIPIO='BayÃ¡rcal­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bedmar y Garcíez' where MUNICIPIO='Bedmar y GarcÃ­ez­'
update CASOS_MUNICIPIOS set MUNICIPIO='Begíjar' where MUNICIPIO='BegÃ­jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Belalcázar' where MUNICIPIO='BelalcÃ¡zar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benacazón' where MUNICIPIO='BenacazÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benagalbón' where MUNICIPIO='BenagalbÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benahavís' where MUNICIPIO='BenahavÃ­s­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benalúa' where MUNICIPIO='BenalÃºa­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benalúa de Guadix' where MUNICIPIO='BenalÃºa de Guadix­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benalúa de las Villas' where MUNICIPIO='BenalÃºa de las Villas­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benalauría' where MUNICIPIO='BenalaurÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benalmádena' where MUNICIPIO='BenalmÃ¡dena­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benamejí' where MUNICIPIO='BenamejÃ­­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benaoján' where MUNICIPIO='BenaojÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benarrabá' where MUNICIPIO='BenarrabÃ¡­'
update CASOS_MUNICIPIOS set MUNICIPIO='Benizalón' where MUNICIPIO='BenizalÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Blázquez (Los)' where MUNICIPIO='BlÃ¡zquez (Los)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bollullos de la Mitación' where MUNICIPIO='Bollullos de la MitaciÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Bubión' where MUNICIPIO='BubiÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Busquístar' where MUNICIPIO='BusquÃ­star­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cáñar' where MUNICIPIO='CÃ¡Ã±ar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cádiar' where MUNICIPIO='CÃ¡diar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cádiz' where MUNICIPIO='CÃ¡diz­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cádiz (capital)' where MUNICIPIO='CÃ¡diz (capital)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cájar' where MUNICIPIO='CÃ¡jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cárchel' where MUNICIPIO='CÃ¡rchel­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cárcheles' where MUNICIPIO='CÃ¡rcheles­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cártama' where MUNICIPIO='CÃ¡rtama­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cástaras' where MUNICIPIO='CÃ¡staras­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cóbdar' where MUNICIPIO='CÃ³bdar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cómpeta' where MUNICIPIO='CÃ³mpeta­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cónchar' where MUNICIPIO='CÃ³nchar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Córdoba' where MUNICIPIO='CÃ³rdoba­'
update CASOS_MUNICIPIOS set MUNICIPIO='Córdoba (capital)' where MUNICIPIO='CÃ³rdoba (capital)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Córdoba (distrito)' where MUNICIPIO='CÃ³rdoba (distrito)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Córdoba Norte' where MUNICIPIO='CÃ³rdoba Norte­'
update CASOS_MUNICIPIOS set MUNICIPIO='Córdoba Sur' where MUNICIPIO='CÃ³rdoba Sur­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cañada Rosal' where MUNICIPIO='CaÃ±ada Rosal­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cañaveral de León' where MUNICIPIO='CaÃ±averal de LeÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cañete de las Torres' where MUNICIPIO='CaÃ±ete de las Torres­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cañete la Real' where MUNICIPIO='CaÃ±ete la Real­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cacín' where MUNICIPIO='CacÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Calañas' where MUNICIPIO='CalaÃ±as­'
update CASOS_MUNICIPIOS set MUNICIPIO='Campofrío' where MUNICIPIO='CampofrÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Campotéjar' where MUNICIPIO='CampotÃ©jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Canjáyar' where MUNICIPIO='CanjÃ¡yar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cúllar' where MUNICIPIO='CÃºllar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cúllar Vega' where MUNICIPIO='CÃºllar Vega­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cúllar-Baza' where MUNICIPIO='CÃºllar-Baza­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cútar' where MUNICIPIO='CÃºtar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cardeña' where MUNICIPIO='CardeÃ±a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Carrión de los Céspedes' where MUNICIPIO='CarriÃ³n de los CÃ©spedes­'
update CASOS_MUNICIPIOS set MUNICIPIO='Castaño del Robledo' where MUNICIPIO='CastaÃ±o del Robledo­'
update CASOS_MUNICIPIOS set MUNICIPIO='Castilléjar' where MUNICIPIO='CastillÃ©jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Castilleja de Guzmán' where MUNICIPIO='Castilleja de GuzmÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Castillo de Locubín' where MUNICIPIO='Castillo de LocubÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Castro del Río' where MUNICIPIO='Castro del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cerro de Andévalo (El)' where MUNICIPIO='Cerro de AndÃ©valo (El)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Chilluévar' where MUNICIPIO='ChilluÃ©var­'
update CASOS_MUNICIPIOS set MUNICIPIO='Chite y Talará' where MUNICIPIO='Chite y TalarÃ¡­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cherín' where MUNICIPIO='CherÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Coín' where MUNICIPIO='CoÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cojáyar' where MUNICIPIO='CojÃ¡yar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Condado-Campiña' where MUNICIPIO='Condado-CampiÃ±a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Coria del Río' where MUNICIPIO='Coria del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Corteconcepción' where MUNICIPIO='AlanÃ­'
update CASOS_MUNICIPIOS set MUNICIPIO='Alanís' where MUNICIPIO='CorteconcepciÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cozví­jar' where MUNICIPIO='CozvÃ­jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Cumbres de San Bartolomé' where MUNICIPIO='Cumbres de San BartolomÃ©­'
update CASOS_MUNICIPIOS set MUNICIPIO='Dalías' where MUNICIPIO='DalÃ­as­'
update CASOS_MUNICIPIOS set MUNICIPIO='Dólar' where MUNICIPIO='DÃ³lar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Dí­lar' where MUNICIPIO='DÃ­lar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Dúdar' where MUNICIPIO='DÃºdar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Dúrcal' where MUNICIPIO='DÃºrcal­'
update CASOS_MUNICIPIOS set MUNICIPIO='Doña MarÃ­a Ocaña' where MUNICIPIO='DoÃ±a MarÃ­a OcaÃ±a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Doña Mencí­a' where MUNICIPIO='DoÃ±a MencÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Domingo Pérez de Granada' where MUNICIPIO='Domingo PÃ©rez de Granada­'
update CASOS_MUNICIPIOS set MUNICIPIO='El Cerro de Andévalo' where MUNICIPIO='El Cerro de AndÃ©valo­'
update CASOS_MUNICIPIOS set MUNICIPIO='El Madroño' where MUNICIPIO='El MadroÃ±o­'
update CASOS_MUNICIPIOS set MUNICIPIO='El Puerto de Santa María' where MUNICIPIO='El Puerto de Santa MarÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Escañuela' where MUNICIPIO='EscaÃ±uela­'
update CASOS_MUNICIPIOS set MUNICIPIO='Escúllar' where MUNICIPIO='EscÃºllar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Escúzar' where MUNICIPIO='EscÃºzar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Faraján' where MUNICIPIO='FarajÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Fernán-Núñez' where MUNICIPIO='FernÃ¡n-NÃºÃ±ez­'
update CASOS_MUNICIPIOS set MUNICIPIO='Fiñana' where MUNICIPIO='FiÃ±ana­'
update CASOS_MUNICIPIOS set MUNICIPIO='Fondón' where MUNICIPIO='FondÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Fuentes de Andalucía' where MUNICIPIO='Fuentes de AndalucÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Fuente-Tójar' where MUNICIPIO='Fuente-TÃ³jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Gádor' where MUNICIPIO='GÃ¡dor­'
update CASOS_MUNICIPIOS set MUNICIPIO='Génave' where MUNICIPIO='GÃ©nave­'
update CASOS_MUNICIPIOS set MUNICIPIO='Gérgal' where MUNICIPIO='GÃ©rgal­'
update CASOS_MUNICIPIOS set MUNICIPIO='Güéjar Sierra' where MUNICIPIO='GÃ¼Ã©jar Sierra­'
update CASOS_MUNICIPIOS set MUNICIPIO='Güéjar' where MUNICIPIO='GÃ¼evÃ©jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Garcíez' where MUNICIPIO='GarciÃ©z­'
update CASOS_MUNICIPIOS set MUNICIPIO='Gaucín' where MUNICIPIO='GaucÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Gibraleón' where MUNICIPIO='GibraleÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Granada de Río-Tinto (La)' where MUNICIPIO='Granada de RÃ­o-Tinto (La)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Guájar Alto' where MUNICIPIO='GuÃ¡jar Alto­'
update CASOS_MUNICIPIOS set MUNICIPIO='Guájares (Los)' where MUNICIPIO='GuÃ¡jares (Los)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Guadalcázar' where MUNICIPIO='GuadalcÃ¡zar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Guardia de Jaén (La)' where MUNICIPIO='Guardia de JaÃ©n (La)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Guarromán' where MUNICIPIO='GuarromÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huécija' where MUNICIPIO='HuÃ©cija­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huélago' where MUNICIPIO='HuÃ©lago­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huéneja' where MUNICIPIO='HuÃ©neja­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huércal de Almerí­a' where MUNICIPIO='HuÃ©rcal de AlmerÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huércal-Overa' where MUNICIPIO='HuÃ©rcal-Overa­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huéscar' where MUNICIPIO='HuÃ©scar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huétor de Santillán' where MUNICIPIO='HuÃ©tor de SantillÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huétor TÃ¡jar' where MUNICIPIO='HuÃ©tor TÃ¡jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huétor Vega' where MUNICIPIO='HuÃ©tor Vega­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huévar' where MUNICIPIO='HuÃ©var­'
update CASOS_MUNICIPIOS set MUNICIPIO='Huévar del Aljarafe' where MUNICIPIO='HuÃ©var del Aljarafe­'
update CASOS_MUNICIPIOS set MUNICIPIO='Instinción' where MUNICIPIO='InstinciÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Istán' where MUNICIPIO='IstÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Iznájar' where MUNICIPIO='IznÃ¡jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Játar' where MUNICIPIO='JÃ¡tar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jérez del Marquesado' where MUNICIPIO='JÃ©rez del Marquesado­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jódar' where MUNICIPIO='JÃ³dar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jaén' where MUNICIPIO='JaÃ©n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jaén (capital)' where MUNICIPIO='JaÃ©n (capital)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jaén (distrito)' where MUNICIPIO='JaÃ©n (distrito)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jaén Nordeste' where MUNICIPIO='JaÃ©n Nordeste­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jaén Norte' where MUNICIPIO='JaÃ©n Norte­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jaén Sur' where MUNICIPIO='JaÃ©n Sur­'
update CASOS_MUNICIPIOS set MUNICIPIO='Júzcar' where MUNICIPIO='JÃºzcar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Jorairátar' where MUNICIPIO='JorairÃ¡tar­'
update CASOS_MUNICIPIOS set MUNICIPIO='La Granada de Río-Tinto' where MUNICIPIO='La Granada de RÃ­o-Tinto­'
update CASOS_MUNICIPIOS set MUNICIPIO='La Guardia de Jaén' where MUNICIPIO='La Guardia de JaÃ©n­'
update CASOS_MUNICIPIOS set MUNICIPIO='La Línea de la Concepción' where MUNICIPIO='La LÃ­nea de la ConcepciÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='La Malahá' where MUNICIPIO='La MalahÃ¡'
update CASOS_MUNICIPIOS set MUNICIPIO='La Puebla del Río' where MUNICIPIO='La Puebla del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='La Roda de Andalucía' where MUNICIPIO='La Roda de AndalucÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Láchar' where MUNICIPIO='LÃ¡char­'
update CASOS_MUNICIPIOS set MUNICIPIO='Láujar de Andarax' where MUNICIPIO='LÃ¡ujar de Andarax­'
update CASOS_MUNICIPIOS set MUNICIPIO='Líjar' where MUNICIPIO='LÃ­jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Línea de la Concepción (La)' where MUNICIPIO='LÃ­nea de la ConcepciÃ³n (La)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Lanjarón' where MUNICIPIO='LanjarÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Lúcar' where MUNICIPIO='LÃºcar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Lújar' where MUNICIPIO='LÃºjar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Las Navas de la Concepción' where MUNICIPIO='Las Navas de la ConcepciÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Lecrín' where MUNICIPIO='LecrÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Lentegí' where MUNICIPIO='LentegÃ­­'
update CASOS_MUNICIPIOS set MUNICIPIO='Lora del Río' where MUNICIPIO='Lora del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Los Blázquez' where MUNICIPIO='Los BlÃ¡zquez­'
update CASOS_MUNICIPIOS set MUNICIPIO='Los Guájares' where MUNICIPIO='Los GuÃ¡jares­'
update CASOS_MUNICIPIOS set MUNICIPIO='Lubrín' where MUNICIPIO='LubrÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Lupión' where MUNICIPIO='LupiÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Málaga' where MUNICIPIO='MÃ¡laga­'
update CASOS_MUNICIPIOS set MUNICIPIO='Málaga (capital)' where MUNICIPIO='MÃ¡laga (capital)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Málaga (distrito)' where MUNICIPIO='MÃ¡laga (distrito)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Madroño (El)' where MUNICIPIO='MadroÃ±o (El)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Malá (La)' where MUNICIPIO='MalÃ¡ (La)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Malahá (La)' where MUNICIPIO='MalahÃ¡ (La)­'
update CASOS_MUNICIPIOS set MUNICIPIO='María' where MUNICIPIO='MarÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Martín de la Jara' where MUNICIPIO='MartÃ­n de la Jara­'
update CASOS_MUNICIPIOS set MUNICIPIO='Mecina-Bombarón' where MUNICIPIO='Mecina-BombarÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Melegís' where MUNICIPIO='MelegÃ­s­'
update CASOS_MUNICIPIOS set MUNICIPIO='Mengíbar' where MUNICIPIO='MengÃ­bar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Moclín' where MUNICIPIO='MoclÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Mojácar' where MUNICIPIO='MojÃ¡car­'
update CASOS_MUNICIPIOS set MUNICIPIO='Molvízar' where MUNICIPIO='MolvÃ­zar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Mondújar' where MUNICIPIO='MondÃºjar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Montalbán de Córdoba' where MUNICIPIO='MontalbÃ¡n de CÃ³rdoba­'
update CASOS_MUNICIPIOS set MUNICIPIO='Montefrío' where MUNICIPIO='MontefrÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Montejícar' where MUNICIPIO='MontejÃ­car­'
update CASOS_MUNICIPIOS set MUNICIPIO='Montizón' where MUNICIPIO='MontizÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Morón de la Frontera' where MUNICIPIO='MorÃ³n de la Frontera­'
update CASOS_MUNICIPIOS set MUNICIPIO='Morelábor' where MUNICIPIO='MorelÃ¡bor­'
update CASOS_MUNICIPIOS set MUNICIPIO='Municipio de Almería sin especificar' where MUNICIPIO='Municipio de AlmerÃ­a sin especificar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Municipio de Cádiz sin especificar' where MUNICIPIO='Municipio de CÃ¡diz sin especificar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Municipio de Córdoba sin especificar' where MUNICIPIO='Municipio de CÃ³rdoba sin especificar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Municipio de Jaén sin especificar' where MUNICIPIO='Municipio de JaÃ©n sin especificar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Municipio de Málaga sin especificar' where MUNICIPIO='Municipio de MÃ¡laga sin especificar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Níjar' where MUNICIPIO='NÃ­jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Nívar' where MUNICIPIO='NÃ­var­'
update CASOS_MUNICIPIOS set MUNICIPIO='Navas de la Concepción (Las)' where MUNICIPIO='Navas de la ConcepciÃ³n (Las)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Nigüelas' where MUNICIPIO='NigÃ¼elas­'
update CASOS_MUNICIPIOS set MUNICIPIO='Ocaña' where MUNICIPIO='OcaÃ±a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Ogíjares' where MUNICIPIO='OgÃ­jares­'
update CASOS_MUNICIPIOS set MUNICIPIO='Ojén' where MUNICIPIO='OjÃ©n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Olías' where MUNICIPIO='OlÃ­as­'
update CASOS_MUNICIPIOS set MUNICIPIO='Olula del Río' where MUNICIPIO='Olula del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Otívar' where MUNICIPIO='OtÃ­var­'
update CASOS_MUNICIPIOS set MUNICIPIO='Pórtugos' where MUNICIPIO='PÃ³rtugos­'
update CASOS_MUNICIPIOS set MUNICIPIO='Píñar' where MUNICIPIO='PÃ­Ã±ar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Palma del Río' where MUNICIPIO='Palma del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Palomares del Río' where MUNICIPIO='Palomares del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Paterna del Río' where MUNICIPIO='Paterna del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Peñaflor' where MUNICIPIO='PeÃ±aflor­'
update CASOS_MUNICIPIOS set MUNICIPIO='Peñarroya-Pueblonuevo' where MUNICIPIO='PeÃ±arroya-Pueblonuevo­'
update CASOS_MUNICIPIOS set MUNICIPIO='Peñarrubia' where MUNICIPIO='PeÃ±arrubia­'
update CASOS_MUNICIPIOS set MUNICIPIO='Pedro Martínez' where MUNICIPIO='Pedro MartÃ­nez­'
update CASOS_MUNICIPIOS set MUNICIPIO='Polícar' where MUNICIPIO='PolÃ­car­'
update CASOS_MUNICIPIOS set MUNICIPIO='Poniente de Almería' where MUNICIPIO='Poniente de AlmerÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Pozo Alcón' where MUNICIPIO='Pozo AlcÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Priego de Córdoba' where MUNICIPIO='Priego de CÃ³rdoba­'
update CASOS_MUNICIPIOS set MUNICIPIO='Puebla de Guzmán' where MUNICIPIO='Puebla de GuzmÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Puebla del Rí­o' where MUNICIPIO='Puebla del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Puebla del Rí­o' where MUNICIPIO='Puebla del RÃ­o (La)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Puente de Génave' where MUNICIPIO='Puente de GÃ©nave­'
update CASOS_MUNICIPIOS set MUNICIPIO='Puerto de Santa María (El)' where MUNICIPIO='Puerto de Santa MarÃ­a (El)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Pulpí' where MUNICIPIO='PulpÃ­­'
update CASOS_MUNICIPIOS set MUNICIPIO='Punta Umbría' where MUNICIPIO='Punta UmbrÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Quéntar' where MUNICIPIO='QuÃ©ntar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Rágol' where MUNICIPIO='RÃ¡gol­'
update CASOS_MUNICIPIOS set MUNICIPIO='Restábal' where MUNICIPIO='RestÃ¡bal­'
update CASOS_MUNICIPIOS set MUNICIPIO='Rincón de la Victoria' where MUNICIPIO='RincÃ³n de la Victoria­'
update CASOS_MUNICIPIOS set MUNICIPIO='Roda de Andalucía (La)' where MUNICIPIO='Roda de AndalucÃ­a (La)­'
update CASOS_MUNICIPIOS set MUNICIPIO='Salobreña' where MUNICIPIO='SalobreÃ±a­'
update CASOS_MUNICIPIOS set MUNICIPIO='San Bartolomé de la Torre' where MUNICIPIO='San BartolomÃ© de la Torre­'
update CASOS_MUNICIPIOS set MUNICIPIO='San José del Valle' where MUNICIPIO='San JosÃ© del Valle­'
update CASOS_MUNICIPIOS set MUNICIPIO='San Martín del Tesorillo' where MUNICIPIO='San MartÃ­n del Tesorillo­'
update CASOS_MUNICIPIOS set MUNICIPIO='San Nicolás del Puerto' where MUNICIPIO='San NicolÃ¡s del Puerto­'
update CASOS_MUNICIPIOS set MUNICIPIO='San Sebastián de los Ballesteros' where MUNICIPIO='San SebastiÃ¡n de los Ballesteros­'
update CASOS_MUNICIPIOS set MUNICIPIO='San Silvestre de Guzmán' where MUNICIPIO='San Silvestre de GuzmÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Sanlúcar de Barrameda' where MUNICIPIO='SanlÃºcar de Barrameda­'
update CASOS_MUNICIPIOS set MUNICIPIO='Sanlúcar de Guadiana' where MUNICIPIO='SanlÃºcar de Guadiana­'
update CASOS_MUNICIPIOS set MUNICIPIO='Sanlúcar la Mayor' where MUNICIPIO='SanlÃºcar la Mayor­'
update CASOS_MUNICIPIOS set MUNICIPIO='Santa Bárbara de Casa' where MUNICIPIO='Santa BÃ¡rbara de Casa­'
update CASOS_MUNICIPIOS set MUNICIPIO='Santa Fe de Mondújar' where MUNICIPIO='Santa Fe de MondÃºjar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Santo Tomé' where MUNICIPIO='Santo TomÃ©­'
update CASOS_MUNICIPIOS set MUNICIPIO='Senés' where MUNICIPIO='SenÃ©s­'
update CASOS_MUNICIPIOS set MUNICIPIO='Serón' where MUNICIPIO='SerÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Serranía' where MUNICIPIO='SerranÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Sierra de Cádiz' where MUNICIPIO='Sierra de CÃ¡diz­'
update CASOS_MUNICIPIOS set MUNICIPIO='Sierra de Huelva-Andévalo Central' where MUNICIPIO='Sierra de Huelva-AndÃ©valo Central­'
update CASOS_MUNICIPIOS set MUNICIPIO='Somontín' where MUNICIPIO='SomontÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Soportújar' where MUNICIPIO='SoportÃºjar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Sorvilán' where MUNICIPIO='SorvilÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Suflí' where MUNICIPIO='SuflÃ­­'
update CASOS_MUNICIPIOS set MUNICIPIO='Tí­jola' where MUNICIPIO='TÃ­jola­'
update CASOS_MUNICIPIOS set MUNICIPIO='Torre Alháquime' where MUNICIPIO='Torre AlhÃ¡quime­'
update CASOS_MUNICIPIOS set MUNICIPIO='Torres de Albánchez' where MUNICIPIO='Torres de AlbÃ¡nchez­'
update CASOS_MUNICIPIOS set MUNICIPIO='Torvizcón' where MUNICIPIO='TorvizcÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Totalán' where MUNICIPIO='TotalÃ¡n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Trevélez' where MUNICIPIO='TrevÃ©lez­'
update CASOS_MUNICIPIOS set MUNICIPIO='Turón' where MUNICIPIO='TurÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Ugíjar' where MUNICIPIO='UgÃ­jar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Urrácal' where MUNICIPIO='UrrÃ¡cal­'
update CASOS_MUNICIPIOS set MUNICIPIO='Válor' where MUNICIPIO='VÃ¡lor­'
update CASOS_MUNICIPIOS set MUNICIPIO='Vélez de Benaudalla' where MUNICIPIO='VÃ©lez de Benaudalla­'
update CASOS_MUNICIPIOS set MUNICIPIO='Vélez-Blanco' where MUNICIPIO='VÃ©lez-Blanco­'
update CASOS_MUNICIPIOS set MUNICIPIO='Vélez-MÃ¡laga' where MUNICIPIO='VÃ©lez-MÃ¡laga­'
update CASOS_MUNICIPIOS set MUNICIPIO='Vélez-Rubio' where MUNICIPIO='VÃ©lez-Rubio­'
update CASOS_MUNICIPIOS set MUNICIPIO='Ví­car' where MUNICIPIO='VÃ­car­'
update CASOS_MUNICIPIOS set MUNICIPIO='Valdepeñas de Jaén' where MUNICIPIO='ValdepeÃ±as de JaÃ©n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Valencina de la Concepción' where MUNICIPIO='Valencina de la ConcepciÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Valle de Abdalajís' where MUNICIPIO='Valle de AbdalajÃ­s­'
update CASOS_MUNICIPIOS set MUNICIPIO='Valle del Zalabí' where MUNICIPIO='Valle del ZalabÃ­­'
update CASOS_MUNICIPIOS set MUNICIPIO='Ví­znar' where MUNICIPIO='VÃ­znar­'
update CASOS_MUNICIPIOS set MUNICIPIO='Viñuela' where MUNICIPIO='ViÃ±uela­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villa del Río' where MUNICIPIO='Villa del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villafranca de Córdoba' where MUNICIPIO='Villafranca de CÃ³rdoba­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villamartín' where MUNICIPIO='VillamartÃ­n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villanueva de Córdoba' where MUNICIPIO='Villanueva de CÃ³rdoba­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villanueva de la Concepción' where MUNICIPIO='Villanueva de la ConcepciÃ³n­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villanueva del Río y Minas' where MUNICIPIO='Villanueva del RÃ­o y Minas­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villanueva Mesía' where MUNICIPIO='Villanueva MesÃ­a­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villaverde del Río' where MUNICIPIO='Villaverde del RÃ­o­'
update CASOS_MUNICIPIOS set MUNICIPIO='Villaviciosa de Córdoba' where MUNICIPIO='Villaviciosa de CÃ³rdoba­'
update CASOS_MUNICIPIOS set MUNICIPIO='Yátor' where MUNICIPIO='YÃ¡tor­'
update CASOS_MUNICIPIOS set MUNICIPIO='Zújar' where MUNICIPIO='ZÃºjar­'
