CREATE TABLE A_FINANCIERA (
	FECHA DATE NOT NULL,
	MERCADO VARCHAR(100) NOT NULL,
	COD_PAIS VARCHAR(5) FOREIGN KEY REFERENCES dbo.PAIS(COD_PAIS),
	APERTURA NUMERIC,
	CIERRE NUMERIC,
	MAXIMO NUMERIC,
	MINIMO NUMERIC,
	VOLUMEN NUMERIC
	PRIMARY KEY(FECHA, MERCADO)
);
