CREATE TABLE FACT_COVID_P (
	FECHA DATE NOT NULL,
	ID_GRUPO_EDAD INT NOT NULL FOREIGN KEY REFERENCES DIM_GRUPO_EDAD(ID_GRUPO_EDAD),
	ID_SEXO INT NOT NULL FOREIGN KEY REFERENCES DIM_SEXO(ID_SEXO),
	COD_PROVINCIA VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES DIM_PROVINCIAS(COD_PROVINCIA),
	NUM_CASOS INT,
	NUM_DEFUNCIONES INT,
	NUM_UCI INT,
	NUM_HOSPITALIZACIONES INT
	PRIMARY KEY (FECHA, ID_GRUPO_EDAD, ID_SEXO, COD_PROVINCIA)
);