CREATE TABLE FACT_IA(
	[FECHA] [date] NOT NULL,
	[COD_PROVINCIA] [VARCHAR](5),
	[COD_SEXO] [VARCHAR](5),
	[COD_CCAA][INT],
	[PORCENTAJE_ERROR_MEDIO] [VARCHAR](255),
	[LIMITE_INFERIOR] [VARCHAR](255),
	[LIMITE_SUPERIOR] [VARCHAR](255),
	[IA] [VARCHAR](255),
	[IA_PREDICCION] [VARCHAR](255)
)