CREATE TABLE A_COVID_P (
	FECHA DATE NOT NULL,
	EDAD VARCHAR(100) NOT NULL,
	SEXO VARCHAR(5) NOT NULL,
	COD_PROVINCIA VARCHAR(5)  FOREIGN KEY REFERENCES dbo.PROVINCIA(COD_PROVINCIA),
	NUM_CASOS INT,
	NUM_DEFUNCIONES INT,
	NUM_UCI INT,
	NUM_HOSPITALIZACIONES INT
	PRIMARY KEY (FECHA,EDAD,SEXO, COD_PROVINCIA)
);