CREATE TABLE VACUNAS_PROVINCIAS (
	FECHA DATE NOT NULL,
	TIPO VARCHAR(255),
	COD_PROVINCIA VARCHAR(5)  FOREIGN KEY REFERENCES dbo.PROVINCIA(COD_PROVINCIA),
	TOTAL_ADMINISTRADAS INT,
	PRIMARY KEY (FECHA,TIPO,COD_PROVINCIA)
);