CREATE TABLE FACT_VACUNAS_PROVINCIAS (
	FECHA DATE NOT NULL,
	ID_TIPO INT NOT NULL FOREIGN KEY REFERENCES DIM_TIPOS_VACUNAS(ID_TIPO),
	COD_PROVINCIA VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES DIM_PROVINCIAS(COD_PROVINCIA),
	DOSIS_ADMINISTRADAS INT
	PRIMARY KEY (FECHA, ID_TIPO, COD_PROVINCIA)
);