
CREATE TABLE [dbo].[FACT_COVID_P](
	[FECHA] [date] NOT NULL,
	[ID_GRUPO_EDAD] [int] NOT NULL,
	[ID_SEXO] [int] NOT NULL,
	[COD_PROVINCIA] [varchar](5) NOT NULL,
	[NUM_CASOS] [int] NULL,
	[NUM_DEFUNCIONES] [int] NULL,
	[NUM_UCI] [int] NULL,
	[NUM_HOSPITALIZACIONES] [int] NULL,
	[COD_CCAA] [int] NULL,
	[COD_PAIS] [varchar](5) NULL,
PRIMARY KEY CLUSTERED 
(
	[FECHA] ASC,
	[ID_GRUPO_EDAD] ASC,
	[ID_SEXO] ASC,
	[COD_PROVINCIA] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FACT_COVID_P]  WITH CHECK ADD FOREIGN KEY([COD_CCAA])
REFERENCES [dbo].[DIM_CCAA] ([COD_CCAA])
GO

ALTER TABLE [dbo].[FACT_COVID_P]  WITH CHECK ADD FOREIGN KEY([COD_PROVINCIA])
REFERENCES [dbo].[DIM_PROVINCIAS] ([COD_PROVINCIA])
GO

ALTER TABLE [dbo].[FACT_COVID_P]  WITH CHECK ADD FOREIGN KEY([COD_PAIS])
REFERENCES [dbo].[DIM_PAISES] ([COD_PAIS])
GO

ALTER TABLE [dbo].[FACT_COVID_P]  WITH CHECK ADD FOREIGN KEY([ID_GRUPO_EDAD])
REFERENCES [dbo].[DIM_GRUPO_EDAD] ([ID_GRUPO_EDAD])
GO

ALTER TABLE [dbo].[FACT_COVID_P]  WITH CHECK ADD FOREIGN KEY([ID_SEXO])
REFERENCES [dbo].[DIM_SEXO] ([ID_SEXO])
GO
