CREATE TABLE PROVINCIA (
	COD_PROVINCIA VARCHAR(5) NOT NULL PRIMARY KEY,
	PROVINCIA VARCHAR(255),
	COD_CCAA INT NOT NULL FOREIGN KEY REFERENCES COMUNIDAD_AUTONOMA(COD_CCAA),
	LATITUD FLOAT,
	LONGITUD FLOAT,
);