CREATE TABLE VACUNAS_CCAA (
	FECHA DATE NOT NULL,
	TIPO VARCHAR(100) NOT NULL,
	COD_CCAA INT FOREIGN KEY REFERENCES COMUNIDAD_AUTONOMA(COD_CCAA),
	TOTAL_ADMINISTRADAS FLOAT,
	RECIBIDAS FLOAT,
	PORCENTAJE_ADM_RECV FLOAT
	PRIMARY KEY (FECHA,TIPO,COD_CCAA)
);