CREATE TABLE MUNICIPIO (
	COD_MUNICIPIO VARCHAR(10) NOT NULL PRIMARY KEY,
	COD_PROVINCIA VARCHAR(5) FOREIGN KEY REFERENCES PROVINCIA(COD_PROVINCIA),
	COD_POSTAL VARCHAR(255),
	MUNICIPIO VARCHAR(255)
);