CREATE TABLE FACT_A_FINANCIERA (
	FECHA DATE NOT NULL,
	ID_MERCADO INT FOREIGN KEY REFERENCES DIM_MERCADOS(ID_MERCADO),
	COD_PAIS VARCHAR(5) FOREIGN KEY REFERENCES DIM_PAISES(COD_PAIS),
	APERTURA NUMERIC,
	CIERRE NUMERIC,
	MAXIMO NUMERIC,
	MINIMO NUMERIC,
	VOLUMEN NUMERIC
);